"""
linalg/svd.py
Singular Value Decomposition (SVD) from scratch and related theorems.
"""
import numpy as np

def svd_from_scratch(X: np.ndarray, tol: float = 1e-10) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, int]:
    # 1. Diagonalize S = X.T @ X via symmetric eigenvalue decomposition
    m, n = X.shape
    XTx = X.T @ X
    eigenvalues, V = np.linalg.eigh(XTx)

    # 2. Sort eigenvalues and eigenvectors in descending order, extract sigma, determine rank r
    eigenvalues = eigenvalues[::-1]  
    V = V[:, ::-1]  
    
    # Clean numerical noise (force near-zero eigenvalues to be exactly 0)
    eigenvalues = np.where(eigenvalues < tol, 0.0, eigenvalues)
    r = int(np.sum(eigenvalues > 0))
    sing_values = np.sqrt(eigenvalues[:r])

    # 3. Construct U_r = X @ V_r / sigma
    V_r = V[:, :r]
    U_r = X @ V_r / sing_values
    
    # 4. Complete the orthonormal basis for U (dimension m x m) using modified Gram-Schmidt
    U = np.zeros((m, m))
    U[:, :r] = U_r.copy()  # Fill the first r columns with U_r
    
    # Fill the remaining (m - r) columns by projecting canonical basis vectors
    current_col = r
    basis_m = np.eye(m)
    
    for j in range(m):
        if current_col == m:
            break
        
        e_j = basis_m[:, j].copy()
        
        # Project e_j onto the orthogonal subspace generated by ALL columns discovered so far
        # U_computed represents the current orthogonal matrix state up to index 'current_col'
        U_computed = U[:, :current_col]
        e_j -= U_computed @ (U_computed.T @ e_j)
        
        norm_e_j = np.linalg.norm(e_j)
        if norm_e_j > tol:
            U[:, current_col] = e_j / norm_e_j  # Insert normalized orthogonal vector directly
            current_col += 1

    # 5. Build full matrices and return structures
    Vt = V.T.copy()
    Sigma = np.zeros((m, n))
    Sigma[:r, :r] = np.diag(sing_values)
    
    # Returns (U, Sigma, Vt, sing_values, rank)
    return (U, Sigma, Vt, sing_values, r)


def truncated_svd(X: np.ndarray, k: int) -> tuple:
    # TODO: Appeler svd_from_scratch, puis ne garder que les k premières colonnes/lignes.
    U,Sigma,Vt,_, r = svd_from_scratch(X)
    k = min(k,r)
    U_k = U[:, :k]
    Sigma_k = Sigma[:k, :k]
    Vt_k = Vt[:k, :]
    return (U_k, Sigma_k, Vt_k)
    

def eckart_young_validation(X: np.ndarray, k: int) -> float:
    """Calcule l'erreur d'approximation ||X - X_k||_F."""
    # TODO: Construire X_k via truncated_svd et retourner la norme de Frobenius du résidu.
    U_k, Sigma_k, Vt_k = truncated_svd(X, k)
    X_k = U_k @ Sigma_k @ Vt_k
    error = np.linalg.norm(X - X_k, 'fro')  
    return error